### ISSUE TITLE
add example

### ISSUE THREAD

**Issue by macbef** [stm32duino/VL6180X#4]
This is not really an "issue", but would you mind adding a simple example?

Thanks a lot for the great work!

**Comment by cparata** [comment]
Hi @macbef ,
the reason is because the library is generic enough to be used in whatever board that mounts this component and I do not want to limit the library at any specific board.  Anyway, if you describe your hardware setup, I can help you to write a sketch that works on your specific hardware.
Best Regards,
Carlo
