### ISSUE TITLE
Macro trouble

### ISSUE THREAD

**Issue by bvaccaro** [stm32duino/VL6180X#7]
I am having trouble calling the VL1680x_ClearAllInterrupt() macro from my sketch.  I defined the macro directly in my sketch as #define ClearAllInterrupt() ClearInterrupt(INTERRUPT_CLEAR_ERROR|INTERRUPT_CLEAR_RANGING|INTERRUPT_CLEAR_ALS) and it works.  I was getting out of scope errors during compilation using the macro defined in your header and c++ files.  Three questions.  Why do you define it in both files?  How can I just use the one defined in the library (does it work for you?)?  Can you also declare INTR_POL_LOW and INTR_POL_HIGH somewhere?  It was in the VL6180 library and should be here as well I would think.  Especially since it is mentioned in the code comments.

**Comment by cparata** [comment]
Hello @bvaccaro ,
the reason is because the define is:
```
#define VL6180x_AlsClearInterrupt(dev) VL6180x_ClearInterrupt(dev, INTERRUPT_CLEAR_ALS)
```
and VL6180x_ClearInterrupt is a protected method, so it cannot be used outside the class.
Anyway, you can call:
```
ClearInterrupt(INTERRUPT_CLEAR_ERROR|INTERRUPT_CLEAR_RANGING|INTERRUPT_CLEAR_ALS);
```
at the application level to get the same behavior.

Regarding the other point, you can use directly 0 and 1 instead of INTR_POL_LOW and INTR_POL_HIGH to get the same behavior.
Best Regards,
Carlo
